### ISSUE TITLE
Feature: User can view property listings

### ISSUE THREAD

**Issue by Rachael-Kim** [Rachael-Kim/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

-Users can view listed properties from the website. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/63431636/139964597-d85a60c3-4c55-4db8-982c-9ffc1a2d3c6f.png)
![image](https://user-images.githubusercontent.com/63431636/139964625-eb4349cd-0d36-4677-ba09-e26ef6d0561c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to GET all property listing. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for rendering each properties' title, description, and price to the webpage.

### 🧑‍⚕️ Clean Up

- [x] Create a separate file for this feature and export class.
- [x] Work on CSS
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
