### ISSUE TITLE
Feature: User can favorite a listing

### ISSUE THREAD

**Issue by Rachael-Kim** [Rachael-Kim/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to save and view homes they selected as favorites. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when the user clicks on the heart icon (on the top right corner of each picture of the listed home), an image will be added to favorites list. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/63431636/139965375-33520089-0c18-4e49-8191-a22d258325de.png)
![image](https://user-images.githubusercontent.com/63431636/139965399-29deafea-217f-49aa-b5a5-ef0379cacda6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to GET favorite list. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for users favoriting listed property.
- [x] Update component to render updated favorited list. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
